apiVersion: v1
kind: Secret
metadata:
  name: products-secret
type: Opaque
stringData:
  ENVIRONMENT: "local"
  API_V1_STR: "/api/v1"

  POSTGRES_SERVER: "products_db"
  POSTGRES_PORT: "5432"
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "postgres"
  POSTGRES_DB: "postgres"

  REDIS_HOST: "products_redis"
  REDIS_PORT: "6379"
  REDIS_DB: "0"

  KEYCLOAK_SERVER_URL: "http://keycloak:8080"
  KEYCLOAK_CLIENT_ID: "test"
  KEYCLOAK_CLIENT_SECRET_KEY: "Z53ikQLLC3Jum8WjQsXiaqGQPQyvUUuA"
  KEYCLOAK_REALM_NAME: "test"

  KAFKA_SERVER: "kafka:9092"

  PYTHONPATH: "/app"