apiVersion: v1
kind: Secret
metadata:
  name: users-service-secret
type: Opaque
stringData:
  DEBUG: "1"
  SECRET_KEY: "django-insecure-_tke*d-z&0%yqx7md+181d!g)ad5$ljyvmxh=r2w5f%(amy-b)"

  POSTGRES_NAME: "postgres"
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "postgres"
  POSTGRES_HOST: "users-citus-coordinator"
  POSTGRES_PORT: "5432"

  REDIS_HOST: "users-redis"
  REDIS_PORT: "6379"

  BACKEND_PORT: "8000"

  KEYCLOAK_SERVER_URL: "http://keycloak:8080"
  KEYCLOAK_CLIENT_ID: "test"
  KEYCLOAK_CLIENT_SECRET_KEY: "OHzcKYhNuk561Djo1qjPI0HZLKqdK8Zp"
  KEYCLOAK_REALM_NAME: "test"
  KEYCLOAK_USER_REALM_NAME: "test"
  KEYCLOAK_USERNAME: "testuser"
  KEYCLOAK_PASSWORD: "testuser"

  KAFKA_SERVER: "kafka:9092"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: users-media-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: users-service
  template:
    metadata:
      labels:
        app: users-service
    spec:
      containers:
      - name: users-service
        image: users-service:latest
        imagePullPolicy: Never
        command:
        - sh
        - -c
        - python manage.py migrate && gunicorn config.wsgi:application --bind 0.0.0.0:8000 --workers 1
        ports:
        - containerPort: 8000
        envFrom:
          - secretRef:
              name: users-service-secret
        readinessProbe:
          httpGet:
            path: /admin
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 10
          failureThreshold: 5
        livenessProbe:
          httpGet:
            path: /admin
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 10
          failureThreshold: 5
        volumeMounts:
        - mountPath: /media
          name: media-volume
      volumes:
      - name: media-volume
        persistentVolumeClaim:
          claimName: users-media-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: users-service
spec:
  selector:
    app: users-service
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
  type: ClusterIP