apiVersion: v1
kind: Secret
metadata:
  name: orders-secret
type: Opaque
stringData:
  ENVIRONMENT: "local"
  API_V1_STR: "/api/v1"

  MONGO_INITDB_ROOT_USERNAME: "root"
  MONGO_INITDB_ROOT_PASSWORD: "example"
  MONGO_INITDB_DATABASE: "mongodb"
  MONGO_HOST: "orders_mongodb"
  MONGO_PORT: "27017"

  KEYCLOAK_SERVER_URL: "http://keycloak:8080"
  KEYCLOAK_CLIENT_ID: "test"
  KEYCLOAK_CLIENT_SECRET_KEY: "Z53ikQLLC3Jum8WjQsXiaqGQPQyvUUuA"
  KEYCLOAK_REALM_NAME: "test"

  KAFKA_SERVER: "kafka:9092"